version: '3.8'
services:
  # PostgreSQL Database (Minimal Configuration)
  postgres:
    image: postgres:15-alpine
    container_name: postgres_malaysian_loan
    environment:
      POSTGRES_DB: malaysian_loan_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${MASTER_DB_PASSWORD}
      # Memory optimizations for 2GB VPS
      POSTGRES_SHARED_BUFFERS: 64MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 128MB
      POSTGRES_WORK_MEM: 2MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db-minimal.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./postgresql.minimal.conf:/etc/postgresql/postgresql.conf
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: '0.3'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 10s
      retries: 2

  # Redis Cache (Minimal Configuration)
  redis:
    image: redis:7-alpine
    container_name: redis_malaysian_loan
    command: redis-server --maxmemory 40mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 50m
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 5s
      retries: 2

  # Malaysian Loan Bot (Optimized for 2GB)
  malaysian-loan-bot:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: malaysian_loan_bot
    environment:
      CLIENT_ID: client_001
      CLIENT_NAME: "Malaysian Loan Consultant"
      POSTGRES_HOST: postgres
      POSTGRES_DB: malaysian_loan_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${MASTER_DB_PASSWORD}
      REDIS_HOST: redis
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WHATSAPP_TOKEN: ${MALAYSIAN_LOAN_WHATSAPP_TOKEN}
      # External CRM/ERP connections (your existing infrastructure)
      EXTERNAL_CHATWOOT_URL: ${EXTERNAL_CHATWOOT_URL}
      EXTERNAL_CHATWOOT_TOKEN: ${EXTERNAL_CHATWOOT_TOKEN}
      EXTERNAL_ERP_URL: ${EXTERNAL_ERP_URL}
      EXTERNAL_ERP_TOKEN: ${EXTERNAL_ERP_TOKEN}
      # Memory optimizations
      PYTHON_MEMORY_LIMIT: 1000m
      RAG_BATCH_SIZE: 10
      MAX_CONVERSATION_HISTORY: 20
      WEBHOOK_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1200m  # Tight memory limit
          cpus: '1.5'    # Most CPU for AI processing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 10s
      retries: 3

  # Nginx (Lightweight)
  nginx:
    image: nginx:alpine
    container_name: nginx_elestio
    ports:
      - "80:80"
    volumes:
      - ./nginx.elestio.conf:/etc/nginx/nginx.conf
    depends_on:
      - malaysian-loan-bot
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 15m
          cpus: '0.05'

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge