services:
  # PostgreSQL Database (Minimal Configuration)
  postgres:
    image: postgres:15-alpine
    container_name: postgres_main
    environment:
      POSTGRES_DB: malaysian_loan_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${MASTER_DB_PASSWORD:-defaultpass123}
      # Memory optimizations for 2GB VPS
      POSTGRES_SHARED_BUFFERS: 64MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 128MB
      POSTGRES_WORK_MEM: 2MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db-minimal.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: '0.3'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 10s
      retries: 2

  # Redis Cache (Minimal Configuration)
  redis:
    image: redis:7-alpine
    container_name: redis_main
    command: redis-server --maxmemory 40mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 50m
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 5s
      retries: 2

  # Malaysian Loan Bot (Main Application)
  app:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: app_main
    environment:
      CLIENT_ID: ${CLIENT_ID:-client_001}
      CLIENT_NAME: "Malaysian Loan Consultant"
      POSTGRES_HOST: postgres
      POSTGRES_DB: malaysian_loan_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${MASTER_DB_PASSWORD:-defaultpass123}
      REDIS_HOST: redis
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WHATSAPP_TOKEN: ${MALAYSIAN_LOAN_WHATSAPP_TOKEN}
      # External CRM/ERP connections
      EXTERNAL_CHATWOOT_URL: ${EXTERNAL_CHATWOOT_URL:-http://localhost}
      EXTERNAL_CHATWOOT_TOKEN: ${EXTERNAL_CHATWOOT_TOKEN:-none}
      EXTERNAL_ERP_URL: ${EXTERNAL_ERP_URL:-http://localhost}
      EXTERNAL_ERP_TOKEN: ${EXTERNAL_ERP_TOKEN:-none}
      # Memory optimizations
      PYTHON_MEMORY_LIMIT: 1000m
      RAG_BATCH_SIZE: 10
      MAX_CONVERSATION_HISTORY: 20
      WEBHOOK_PORT: 8080
    ports:
    - "80:8080"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1200m
          cpus: '1.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge
